[package]
name = "supertrader-meta"
version = "0.0.0"
authors = ["Bruda Claudiu-Marcel <claudiu725@yahoo.com>"]
edition = "2018"
publish = false
[dependencies.supertrader]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.42.0"
